### ISSUE TITLE
[BUG]: Flash animation does not appear in 1.20.5

### ISSUE THREAD

**Issue by APiggyInABukkit** [KrLite/Flash#5] opened 2024-04-23 23:35 UTC
### Mod Loader

Fabric

### Minecraft Version

1.20.5

### What Happened?

Hello!
I updated my Minecraft to 1.20.5 and noticed the mod loads fine with no errors but when a screenshot is taken the animation does not show at all.
I checked my logs and no details or errors appear as to why the animation is not showing.

### Steps to Reproduce

Load mod with latest fabric for 1.20.5
Join singleplayer world or muliplayer server
Take screenshot
No animation appears

**Comment by KrLite** [comment] 2024-04-23 23:44
Sorry for that, but you should know that **Flash** does not officially support 1.20.5 for now. Mojang actually made 1.20.5 the 'snapshot' of 1.21, instead of the succeed of 1.20, which means that many breaking changes are made. So does 1.19.4 and such versions. In brief, you will need to wait for the upcoming compatibility with 1.20.5 to make the mod work, and thus this is not a bug, as again, **Flash does not officially support 1.20.5 for now.**

**Comment by KrLite** [comment] 2024-04-23 23:45
I will close this issue as not planned. Please wait for the upcoming versions of **Flash!**

**Closed as not planned** 2024-04-23 23:46 UTC
Labels: bug
