### ISSUE TITLE
Game crash when loading Flash with faded widgets.

### ISSUE THREAD

**Issue by andry4054** [KrLite/Flash#3] opened 2023-07-16 10:09 UTC
![image](https://github.com/KrLite/Flash/assets/31610833/e6723ad0-072b-4b78-b41e-ce565ee34b67)

**Comment by KrLite** [comment] 2023-07-16 10:54
Well, that is quite a silly problem... caused by the difference of Equator's version embedded in Flash and Faded Widgets.
I'll figure that out.

**Comment by KrLite** [comment] 2023-07-16 15:06
Time to update! Fixed in version `v1.2.0`.

**Closed as completed by KrLite** 2023-07-16 15:06 UTC
